#!/bin/bash
BLUE="[38;05;67m"
GREEN="[38;05;107m"
ORANGE="[38;05;179m"
RED="[38;05;167m"
YELLOW="[38;05;222m"
default='\033[0m'
bold='\033[1m'

TPM_SYMLINKS="$HOME/bin"
TPM_PACKAGES="$HOME/.local/tpm"
TPM_CONFIG="$HOME/.tpm.json"

print_warned_if_exists() {
    [[ ! -e $1 ]] && echo -ne "${GREEN}" || echo -ne "${ORANGE}"
    echo -e $1${default}
}

clear
echo -e "${GREEN}Welcome to TPM${default}"
echo ""

echo -en "Where shall I place the symlinks? [ ${BLUE}$TPM_SYMLINKS${default} ]: "
read IN_TPM_SYMLINKS

echo -en "Where shall I place the packages? [ ${BLUE}$TPM_PACKAGES${default} ]: "
read IN_TPM_PACKAGES

echo -en "Where shall I place configuration? [ ${BLUE}$TPM_CONFIG${default} ]: "
read IN_TPM_CONFIG

echo -en "Would you like me to fetch ${bold}jq${default} for you from ${bold}http://stedolan.github.io/jq/download/linux{32,64}/jq${default}? [y/32/64/N]: "
read jqinput

[[ ! -z $IN_TPM_SYMLINKS ]] && TPM_SYMLINKS=$IN_TPM_SYMLINKS
[[ ! -z $IN_TPM_CONFIG ]]   && TPM_CONFIG=$IN_TPM_CONFIG
[[ ! -z $IN_TPM_PACKAGES ]] && TPM_PACKAGES=$IN_TPM_PACKAGES

echo -e ""

echo -en "Symlinks: "
print_warned_if_exists $TPM_SYMLINKS
echo -en "Packages: "
print_warned_if_exists $TPM_PACKAGES
echo -en "Config:   "
print_warned_if_exists $TPM_CONFIG

# Initialize folders
mkdir -p $TPM_SYMLINKS
mkdir -p $TPM_PACKAGES
mkdir -p $TPM_PACKAGES/.aux

# Fetch tpm
[[ ! -e $TPM_PACKAGES/tpm ]] && echo "" && echo -e "Fetching ${bold}tpm${default}" && git clone https://github.com/baabelfish/tpm.git $TPM_PACKAGES/tpm

# Configure
echo "export TPM_SYMLINKS=$TPM_SYMLINKS" > $TPM_PACKAGES/.config
echo "export TPM_PACKAGES=$TPM_PACKAGES" >> $TPM_PACKAGES/.config
echo "export TPM_CONFIG=$TPM_CONFIG" >> $TPM_PACKAGES/.config
echo 'export PATH=$TPM_SYMLINKS:$PATH' >> $TPM_PACKAGES/.config
echo 'source $TPM_PACKAGES/tpm/source' >> $TPM_PACKAGES/.config

# Add symlink to tpm
ln -s $TPM_PACKAGES/tpm/tpm $TPM_SYMLINKS/tpm

# Make it compatible with itself :?
echo "$TPM_SYMLINKS/tpm" > $TPM_PACKAGES/tpm_binaries
echo "" > $TPM_PACKAGES/tpm_source

# jq installation
if [[ $jqinput == "y" ]] || [[ $jqinput == "Y" ]] || [[ $jqinput == "32" ]] || [[ $jqinput == "64" ]]; then
    echo -e "Fetching ${bold}jq${default}"
    [[ -e $TPM_PACKAGES/.aux/jq ]] && rm -f $TPM_PACKAGES/.aux/jq
    cd $TPM_PACKAGES/.aux
    ARCH=$jqinput
    if [[ $ARCH == "y" ]] || [[ $ARCH == "Y" ]]; then ARCH="32"; fi
    wget http://stedolan.github.io/jq/download/linux${ARCH}/jq
    chmod +x $TPM_PACKAGES/.aux/jq
fi

# Copying default ~/.tpm.json
[[ ! -e $TPM_CONFIG ]] && cat $TPM_PACKAGES/tpm/default.tpm.json > $TPM_CONFIG

echo -e ""
echo -e "${GREEN}Now add the following line into your ${bold}~/.bashrc${default}${GREEN} or ${bold}~/.zshrc${default}:"
echo -e "source $TPM_PACKAGES/.config"
