#!/bin/bash
# source ./helpers.sh
# source ./git.sh
# source ./json.sh
source $TPM_PACKAGES/tpm/helpers.sh
source $TPM_PACKAGES/tpm/git.sh
source $TPM_PACKAGES/tpm/json.sh

IFS=$'\n'

COMMAND=''
PACKAGES=()
PARAM_NOCOLOR=0
PARAM_NOCONFIRM=0
PARAM_QUIET=0
PARAM_VERBOSE=0

printHelp() {
    echo "\
Usage: tpm [option] <command>

command := disable [packages] |
           enable  [packages] |
           info    [packages] |
           install [packages] |
           list    [packages] |
           remove  [packages] |
           search  [packages] |
           update  [packages] |

option := --help | --nocolor | --noconfirm | --quiet | --verbose
"
exit 1
}

[[ -z $1 ]] && printHelp

setCommand() {
    if [[ ! -z $COMMAND ]]; then
        PACKAGES=("${PACKAGES[@]}" "$C")
    else
        COMMAND=$1
    fi
}

commandDisable() {
    echo "UNDER CONSTRUCTION: commandDisable"
}

commandEnable() {
    echo "UNDER CONSTRUCTION: commandEnable"
}

commandInfo() {
    if [[ ${#PACKAGES[@]} -ne 1 ]]; then
        echo "You must provide one package name"
    else
        infoOne $1
    fi
}

commandInstall() {
    if [[ ${#PACKAGES[@]} -eq 0 ]]; then
        installConfig
    else
        for i in ${PACKAGES[@]}; do
            installOne $i
        done
    fi
}

commandList() {
    PACKAGES=($(ls $TPM_PACKAGES))
    for i in ${PACKAGES[@]}; do
        listOne $i
    done
}

commandRemove() {
    # TODO Remove symlinks
    # TODO Remove all not in tmp.json file
    for i in ${PACKAGES[@]}; do
        removeOne $i
    done
}

commandSearch() {
    echo "UNDER CONSTRUCTION: commandSearch"
}

commandUpdate() {
    # TODO Clean output
    PACKAGES=($(ls $TPM_PACKAGES))
    for i in ${PACKAGES[@]}; do
        updateOne $i
    done
}


for C in ${*}; do
    case $C in
        'disable') setCommand 'disable' ;;
        'enable')  setCommand 'enable' ;;
        'info')    setCommand 'info' ;;
        'install') setCommand 'install' ;;
        'list')    setCommand 'list' ;;
        'remove')  setCommand 'remove' ;;
        'search')  setCommand 'search' ;;
        'update')  setCommand 'update' ;;
        '--help')
            printHelp
            exit 1
            ;;
        '--nocolor')   PARAM_NOCOLOR=1 ;;
        '--noconfirm') PARAM_NOCONFIRM=1 ;;
        '--quiet')     PARAM_QUIET=1 ;;
        '--verbose')   PARAM_VERBOSE=1 ;;
        *)
            PACKAGES=("${PACKAGES[@]}" "$C")
            ;;
    esac
done

case $COMMAND in
    'disable') commandDisable ;;
    'enable')  commandEnable ;;
    'info')    commandInfo ;;
    'install') commandInstall ;;
    'list')    commandList ;;
    'remove')  commandRemove ;;
    'search')  commandSearch ;;
    'update')  commandUpdate ;;
    *)
        echo "Invalid command"
        exit 1
        ;;
esac
